# Generated by Django 3.2.5 on 2021-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='horizontal',
            field=models.BooleanField(default=False),
        ),
    ]
