# Generated by Django 3.2.5 on 2021-09-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210901_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentresponse',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
